FROM 894932018761.dkr.ecr.eu-west-1.amazonaws.com/node:12-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app
COPY package-lock.json /usr/src/app

RUN npm install --silent
RUN npm install react-scripts --silent

COPY . /usr/src/app

ENV DANGEROUSLY_DISABLE_HOST_CHECK=true

CMD ["npm", "run", "start"]
EXPOSE 3000
